import { FileExtension } from "@/@types/FileExtension";
import { MimeType } from "@/@types/Mimetype";

export const mimetypeToExtension: Record<MimeType, FileExtension> = {
  "application/json": ".json",
  "application/xml": ".xml",
  "application/pdf": ".pdf",
  "application/javascript": ".js",
  "application/octet-stream": ".bin",
  "application/zip": ".zip",
  "application/x-www-form-urlencoded": ".txt",
  "application/sql": ".sql",
  "application/graphql": ".graphql",
  "application/ld+json": ".jsonld",
  "image/jpeg": ".jpeg",
  "image/png": ".png",
  "image/gif": ".gif",
  "image/webp": ".webp",
  "image/svg+xml": ".svg",
  "text/plain": ".txt",
  "text/html": ".html",
  "text/css": ".css",
  "text/csv": ".csv",
  "text/javascript": ".js",
  "text/xml": ".xml",
  "audio/mpeg": ".mp3",
  "audio/ogg": ".ogg",
  "audio/wav": ".wav",
  "video/mp4": ".mp4",
  "video/webm": ".webm",
  "video/ogg": ".ogv",
  "font/woff": ".woff",
  "font/woff2": ".woff2",
  "font/ttf": ".ttf",
  "font/otf": ".otf",
  "multipart/form-data": ".form",
}